### PR TITLE
Fix/add enclosure to feed item

### LINKED ISSUE #147: Add <enclosure> to feed item
Feed items are currently missing `<enclosure>` tag which is required according to Apple guidelines: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Currently represented with `<audio>` inside `<description>`.

### PR DESCRIPTION
**Pull request by davidtowoju**
### Description of the Change

This PR adds `<enclosure>` tag to feed items - https://github.com/10up/simple-podcasting/issues/147 which is required according to Apple guidelines: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Currently, there is a function that is meant to add these tags but it's not working, please see below

https://github.com/10up/simple-podcasting/blob/da4578e8ee565ba5f4a53066546dda7d52e56162/includes/customize-feed.php#L258-L284 

### Why it didn't work :point_up_2:

The filter hook `rss_enclosure` is only fired when a meta key titled `enclosure` is present. Unfortunately the meta data is not present and so the function never runs. Please see https://github.com/WordPress/WordPress/blob/63ea8284a3e57ae289ce9ce39a4469cdc317906a/wp-includes/feed.php#L473-L498 

So, when the meta key is present, WordPress automatically adds the `<enclosure>` and we would not need the above filter at all.

### Alternate Designs

Two solutions were considered. One is to echo the `<enclosure>` tags inside the feed item function and forget about the meta. The other is to add meta data `<enclosure>` to podcasts post and add the right values so WordPress can do its thing.

Following the first solution alone means ignoring the WordPress way. Following the second solution alone means that feeds of existing podcasts will never have the enclosure tag. The best method is to combine both. Add `enclosure` meta data when podcast posts are created, then just before feed items are displayed, hook into the feed item to check if the tag is present. If it is empty, then display the `enclosure` tag.

### Possible Drawbacks

None.
### Verification Process

**Test <enclosure> tag is added to feeds**
- Go to Dashboard->Podcasts to create a new podcast
- Go to Posts and create a new post, add an audio file and attach the post to the podcast you created above
- Go to Dashboard->Podcasts and click on the Podcast Feed URL to see the xml feed
- Look for `<enclosure>` tag inside the podcast `<item>` tag you just created above (it will be present)

**Test enclosure meta key is not needed**
- Fetch the ID of the post and run `get_post_custom(ID)`, you should now see `enclosure` key
- Delete the `enclosure` key by doing `delete_post_meta(ID, 'enclosure');`
- Go to Dashboard->Podcasts and click on the Podcast Feed URL to see the xml feed
- Look for `<enclosure>` tag inside the podcast `<item>` tag you just created above (it will be present)

**Test enclosure meta key gets deleted when attachment is removed**
- Go to the Dashboard->Posts and click on the podcast you created.
- Delete the podcast block item
- Run `get_post_custom(ID)`,  the `enclosure` key should be gone

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

> Fixed - Add `<enclosure>` to feed item.

### Credits

Props @davexpression, @cadic.

### CODE REVIEW

File: includes/customize-feed.php [hunk 1]
```diff
@@ -256,15 +262,13 @@ function feed_item() {
 add_action( 'rss2_item', __NAMESPACE__ . '\feed_item' );
 
 /**
- * Adjust the enclosure feed for podcasts.
+ * Displays the enclosure feed for podcasts.
  *
- * @param  string $enclosure The enclosure (media url).
+ * @param  int $post The post ID.
```
Comment (cadic) [inline includes/customize-feed.php]: Please update the type hint. When called from customize-feed.php:241, the `$post` argument is of type `WP_Post`, and also within this function, `$post` is considered as post object. Probably also needs to typecast with `$post = get_post( $post );` at the top of this function.

File: includes/post-meta-box.php [hunk 2]
```diff
@@ -131,6 +131,10 @@ function save_meta_box( $post_id ) {
 			update_post_meta( $post_id, 'podcast_filesize', $podcast_meta['filesize'] );
 			update_post_meta( $post_id, 'podcast_duration', $podcast_meta['duration'] );
 			update_post_meta( $post_id, 'podcast_mime', $podcast_meta['podcast_mime'] );
+
+			// Add enclosure meta data
+			$enclosure = $podcast_meta['url'] . PHP_EOL . $podcast_meta['filesize'] . PHP_EOL . $podcast_meta['podcast_mime'];
```
Comment (cadic) [inline includes/post-meta-box.php]: In WordPress core [wp-includes/feed.php](https://github.com/WordPress/WordPress/blob/63ea8284a3e57ae289ce9ce39a4469cdc317906a/wp-includes/feed.php#L481) the hardcoded `"\n"` is used to explode the enclosure meta before it will be displayed, and so do you in [assets/js/edit.js:79](https://github.com/10up/simple-podcasting/pull/155/files#diff-1a9dc6a976d2043e93be6d50287f70f13ffb4008efe7d8cb8d491a2e6234703fR79) to combine partials into meta string.

Using `PHP_EOL` here might break the logic on non-Unix systems.

**Review by cadic — CHANGES_REQUESTED** [review]
Thank you @davexpression for this brilliant combination of both approaches. I've left a note about `display_rss_enclosure()` PHPDoc and my concern about using PHP_EOL on metabox save.

I also noticed few unit tests fail after the current change.

**Comment by cadic** [comment]
@davexpression please provide the changelog entry in the PR description

**Comment by davidtowoju** [comment]
@cadic Thanks for reviewing the pr and for spotting the issues. It was from your review I got to know that PHP_EOL may not work in non-Unix environments

**Comment by cadic** [comment]
@davexpression thank you, the code looks great, LGTM!

Added unit test coverage for generated enclosure.

I've discovered new issue not related to the current change, raised a new #157

**Review by cadic — APPROVED** [review]
